[package]
name = "blank"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
description = "A blank screen for illumination"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/linebender/druid.git", optional = true }
glium = { version = "0.28", optional = true }
orbtk = { version = "0.3.1-alpha3", optional = true }
web-view = { version = "0.7", optional = true }
winit = { version = "0.23", optional = true }
cocoa = { version = "0.24", optional = true }
temperagb = { path = "../temperagb" }

[features]
default = [ "win" ]
win = [ "winit", "cocoa" ]

[package.metadata.bundle]
name = "Blank"
identifier = "com.mflima.blank"
icon = [ "res/icon*.png" ]
version = "0.1.0"
category = "public.app-category.utilities"
short_description = "A blank screen for illumination"
